function attire_registry_init(){
	global.attire_pool = ds_map_create()
}

///@function get_attire_info(attire_id)
///@description 获取时装数据
///@param {string}attire_id 时装id
///@return {struct}
function get_attire_info(attire_id){
	return ds_map_find_value(global.attire_pool,attire_id)
}

///@function register_attire(attire_id,attire_data)
///@description 注册时装
///@param {string}attire_id 时装id
///@param {struct}attire_data 时装数据
function register_attire(attire_id,attire_data){
	ds_map_add(global.attire_pool,attire_id,attire_data)
}


function attire_init(){
	attire_registry_init()
	//注册全部卡片时装
	register_attire(
		"ice_egg_pisces",
		{
			"target_card":"ice_egg_boiler_pult",
			"name":"双鱼座精灵",
			"icon":spr_ice_egg_pisces_icon,
			"spr":[spr_ice_egg_pisces,spr_ice_egg_pisces_1,spr_ice_egg_pisces_2],
			"card_slot_icon":[spr_ice_egg_pisces_icon,spr_ice_egg_pisces_icon_1,spr_ice_egg_pisces_icon_2]
		}
	)
	register_attire(
		"water_pipe_libra",
		{
			"target_card":"double_water_pipe",
			"name":"天秤座精灵",
			"icon":spr_water_pipe_libra,
			"spr":[spr_water_pipe_libra,spr_water_pipe_libra_1,spr_water_pipe_libra_2],
			"card_slot_icon":[spr_water_pipe_libra,spr_water_pipe_libra_1,spr_water_pipe_libra_2]
		}
	)
	register_attire(
		"wine_rack_sagittarius",
		{
			"target_card":"triple_wine_rack",
			"name":"射手座精灵",
			"icon":spr_wine_rack_sagittarius_icon,
			"spr":[spr_wine_rack_sagittarius,spr_wine_rack_sagittarius_1,spr_wine_rack_sagittarius_2],
			"card_slot_icon":[spr_wine_rack_sagittarius_icon,spr_wine_rack_sagittarius_icon_1,spr_wine_rack_sagittarius_icon_2]
		}
	)
	register_attire(
		"brazier_taurus",
		{
			"target_card":"brazier",
			"name":"金牛座精灵",
			"icon":spr_brazier_taurus,
			"spr":[spr_brazier_taurus,spr_brazier_taurus_1,spr_brazier_taurus_2],
			"card_slot_icon":[spr_brazier_taurus,spr_brazier_taurus_1,spr_brazier_taurus_2]
		}
	)
	register_attire(
		"large_fire_gemini",
		{
			"target_card":"large_fire",
			"name":"双子座精灵",
			"icon":spr_large_fire_gemini_icon,
			"spr":[spr_large_fire_gemini,spr_large_fire_gemini_1,spr_large_fire_gemini_2],
			"card_slot_icon":[spr_large_fire_gemini_icon,spr_large_fire_gemini_icon_1,spr_large_fire_gemini_icon_2]
		}
	)
	register_attire(
		"takoyaki_cancer",
		{
			"target_card":"takoyaki",
			"name":"巨蟹座精灵",
			"icon":spr_takoyaki_cancer_icon,
			"spr":[spr_takoyaki_cancer,spr_takoyaki_cancer_1,spr_takoyaki_cancer_2],
			"card_slot_icon":[spr_takoyaki_cancer_icon,spr_takoyaki_cancer_icon_1,spr_takoyaki_cancer_icon_2]
		}
	)
	register_attire(
		"gatling_popcorn",
		{
			"target_card":"gatlin_long_bao",
			"name":"玉蜀黍",
			"icon":spr_gatling_popcorn_icon,
			"spr":[spr_gatling_popcorn,spr_gatling_popcorn_1,spr_gatling_popcorn_2],
			"card_slot_icon":[spr_gatling_popcorn_icon,spr_gatling_popcorn_icon_1,spr_gatling_popcorn_icon_2]
		}
	)
	register_attire(
		"rotate_leo",
		{
			"target_card":"rotating_coffee_pot",
			"name":"狮子座精灵",
			"icon":spr_rotate_leo_icon,
			"spr":[spr_rotate_leo,spr_rotate_leo_1,spr_rotate_leo_2],
			"card_slot_icon":[spr_rotate_leo_icon,spr_rotate_leo_icon_1,spr_rotate_leo_icon_2]
		}
	)
	register_attire(
		"melon_virgo",
		{
			"target_card":"melon_shield",
			"name":"处女座精灵",
			"icon":spr_melon_virgo_icon,
			"spr":[spr_melon_virgo_icon,spr_melon_virgo_icon_1,spr_melon_virgo_icon_2],
			"outer_spr":[
				[spr_melon_virgo_outer_1,spr_melon_virgo_outer_1,spr_melon_virgo_outer_1],
				[spr_melon_virgo_1_outer_1,spr_melon_virgo_1_outer_2,spr_melon_virgo_1_outer_3],
				[spr_melon_virgo_2_outer_1,spr_melon_virgo_2_outer_2,spr_melon_virgo_2_outer_3]
			],
			"card_slot_icon":[spr_melon_virgo_icon,spr_melon_virgo_icon_1,spr_melon_virgo_icon_2],
			"inner_spr":[spr_melon_virgo_inner_1,spr_melon_virgo_inner_2,spr_melon_virgo_inner_3]
		}
	)
	register_attire(
		"bubble_maltose",
		{
			"target_card":"soda_bubble",
			"name":"麦芽糖",
			"icon":spr_bubble_maltose_icon,
			"spr":[spr_bubble_maltose_0_0,spr_bubble_maltose_1_0],
			"card_slot_icon":[spr_bubble_maltose_icon,spr_bubble_maltose_icon_1],
		}
	)
	register_attire(
		"lobster_athena",
		{
			"target_card":"curry_lobster_cannon",
			"name":"雅典娜守护",
			"icon":spr_lobster_athena,
			"spr":[spr_lobster_athena,spr_lobster_athena_1,spr_lobster_athena_2],
			"card_slot_icon":[spr_lobster_athena,spr_lobster_athena_1,spr_lobster_athena_2]
		}
	)
	
	//注册全部玩家时装
	register_attire(
		"player_attire_1",
		{
			"target_card":"player",
			"name":"雪球兔兔",
			"icon":spr_player_attire_1_icon,
			"spr":spr_player_attire_1,
		}
	)
	register_attire(
		"player_attire_2",
		{
			"target_card":"player",
			"name":"提拉米苏",
			"icon":spr_player_attire_2_icon,
			"spr":spr_player_attire_2,
		}
	)
	register_attire(
		"player_attire_3",
		{
			"target_card":"player",
			"name":"魔影圣衣",
			"icon":spr_player_attire_3_icon,
			"spr":spr_player_attire_3,
		}
	)
	register_attire(
		"player_attire_4",
		{
			"target_card":"player",
			"name":"公会制服",
			"icon":spr_player_attire_4_icon,
			"spr":spr_player_attire_4,
		}
	)
	register_attire(
		"player_attire_5",
		{
			"target_card":"player",
			"name":"龙族传说",
			"icon":spr_player_attire_5_icon,
			"spr":spr_player_attire_5,
		}
	)
	register_attire(
		"player_attire_6",
		{
			"target_card":"player",
			"name":"神奇精灵",
			"icon":spr_player_attire_6_icon,
			"spr":spr_player_attire_6,
		}
	)
	register_attire(
		"player_attire_7",
		{
			"target_card":"player",
			"name":"双子座情人",
			"icon":spr_player_attire_7_icon,
			"spr":spr_player_attire_7,
		}
	)
	register_attire(
		"player_attire_8",
		{
			"target_card":"player",
			"name":"双子座情人",
			"icon":spr_player_attire_8_icon,
			"spr":spr_player_attire_8,
		}
	)
	register_attire(
		"player_attire_9",
		{
			"target_card":"player",
			"name":"爱莎鼠同人",
			"icon":spr_player_attire_9_icon,
			"spr":spr_player_attire_9,
		}
	)
	register_attire(
		"player_attire_10",
		{
			"target_card":"player",
			"name":"别西卜",
			"icon":spr_player_attire_10_icon,
			"spr":spr_player_attire_10,
		}
	)
	register_attire(
		"player_attire_11",
		{
			"target_card":"player",
			"name":"冰淇淋小姐",
			"icon":spr_player_attire_11_icon,
			"spr":spr_player_attire_11,
		}
	)
	register_attire(
		"player_attire_12",
		{
			"target_card":"player",
			"name":"丁香绮缘",
			"icon":spr_player_attire_12_icon,
			"spr":spr_player_attire_12,
		}
	)
	register_attire(
		"player_attire_13",
		{
			"target_card":"player",
			"name":"梦恋花语",
			"icon":spr_player_attire_13_icon,
			"spr":spr_player_attire_13,
		}
	)
	register_attire(
		"player_attire_14",
		{
			"target_card":"player",
			"name":"探险家",
			"icon":spr_player_attire_14_icon,
			"spr":spr_player_attire_14,
		}
	)
	register_attire(
		"player_attire_15",
		{
			"target_card":"player",
			"name":"桃心公主",
			"icon":spr_player_attire_15_icon,
			"spr":spr_player_attire_15,
		}
	)

	register_attire(
		"player_attire_123uzhenchaxiaozu",
		{
			"target_card":"player",
			"name":"123U侦察小组",
			"icon":spr_player_attire_123uzhenchaxiaozu_icon,
			"spr":spr_player_attire_123uzhenchaxiaozu,
		}
	)
	register_attire(
		"player_attire_babyshugongzhu",
		{
			"target_card":"player",
			"name":"baby鼠公主",
			"icon":spr_player_attire_babyshugongzhu_icon,
			"spr":spr_player_attire_babyshugongzhu,
		}
	)
	register_attire(
		"player_attire_cici",
		{
			"target_card":"player",
			"name":"cici",
			"icon":spr_player_attire_cici_icon,
			"spr":spr_player_attire_cici,
		}
	)
	register_attire(
		"player_attire_wanshengjieqianye",
		{
			"target_card":"player",
			"name":"万圣节前夜",
			"icon":spr_player_attire_wanshengjieqianye_icon,
			"spr":spr_player_attire_wanshengjieqianye,
		}
	)
	register_attire(
		"player_attire_sannianerban",
		{
			"target_card":"player",
			"name":"三年二班",
			"icon":spr_player_attire_sannianerban_icon,
			"spr":spr_player_attire_sannianerban,
		}
	)
	register_attire(
		"player_attire_zhongshixianglongfu",
		{
			"target_card":"player",
			"name":"中式祥龙服",
			"icon":spr_player_attire_zhongshixianglongfu_icon,
			"spr":spr_player_attire_zhongshixianglongfu,
		}
	)
	register_attire(
		"player_attire_zhongqiutaozhuang",
		{
			"target_card":"player",
			"name":"中秋套装",
			"icon":spr_player_attire_zhongqiutaozhuang_icon,
			"spr":spr_player_attire_zhongqiutaozhuang,
		}
	)
	register_attire(
		"player_attire_wanzitou",
		{
			"target_card":"player",
			"name":"丸子头",
			"icon":spr_player_attire_wanzitou_icon,
			"spr":spr_player_attire_wanzitou,
		}
	)
	register_attire(
		"player_attire_guaiguaixiaogongzhu",
		{
			"target_card":"player",
			"name":"乖乖小公主",
			"icon":spr_player_attire_guaiguaixiaogongzhu_icon,
			"spr":spr_player_attire_guaiguaixiaogongzhu,
		}
	)
	register_attire(
		"player_attire_xianlvqiyuan",
		{
			"target_card":"player",
			"name":"仙侣奇缘",
			"icon":spr_player_attire_xianlvqiyuan_icon,
			"spr":spr_player_attire_xianlvqiyuan,
		}
	)
	register_attire(
		"player_attire_peiqijiejie",
		{
			"target_card":"player",
			"name":"佩奇姐姐",
			"icon":spr_player_attire_peiqijiejie_icon,
			"spr":spr_player_attire_peiqijiejie,
		}
	)
	register_attire(
		"player_attire_jiaqirumeng",
		{
			"target_card":"player",
			"name":"佳期如梦",
			"icon":spr_player_attire_jiaqirumeng_icon,
			"spr":spr_player_attire_jiaqirumeng,
		}
	)
	register_attire(
		"player_attire_shiyingshengtutu",
		{
			"target_card":"player",
			"name":"侍应生兔兔",
			"icon":spr_player_attire_shiyingshengtutu_icon,
			"spr":spr_player_attire_shiyingshengtutu,
		}
	)
	register_attire(
		"player_attire_qiaoxinniang",
		{
			"target_card":"player",
			"name":"俏新娘",
			"icon":spr_player_attire_qiaoxinniang_icon,
			"spr":spr_player_attire_qiaoxinniang,
		}
	)
	register_attire(
		"player_attire_xiuxianxiaoxianv",
		{
			"target_card":"player",
			"name":"修仙小侠女",
			"icon":spr_player_attire_xiuxianxiaoxianv_icon,
			"spr":spr_player_attire_xiuxianxiaoxianv,
		}
	)
	register_attire(
		"player_attire_yuanqishaonv",
		{
			"target_card":"player",
			"name":"元气少女",
			"icon":spr_player_attire_yuanqishaonv_icon,
			"spr":spr_player_attire_yuanqishaonv,
		}
	)
	register_attire(
		"player_attire_tuerniang",
		{
			"target_card":"player",
			"name":"兔儿娘",
			"icon":spr_player_attire_tuerniang_icon,
			"spr":spr_player_attire_tuerniang,
		}
	)
	register_attire(
		"player_attire_tunianjixiang",
		{
			"target_card":"player",
			"name":"兔年吉祥",
			"icon":spr_player_attire_tunianjixiang_icon,
			"spr":spr_player_attire_tunianjixiang,
		}
	)
	register_attire(
		"player_attire_tujingguanzhudi",
		{
			"target_card":"player",
			"name":"兔警官朱迪",
			"icon":spr_player_attire_tujingguanzhudi_icon,
			"spr":spr_player_attire_tujingguanzhudi,
		}
	)
	register_attire(
		"player_attire_gongzhuyuqishi",
		{
			"target_card":"player",
			"name":"公主与骑士",
			"icon":spr_player_attire_gongzhuyuqishi_icon,
			"spr":spr_player_attire_gongzhuyuqishi,
		}
	)
	register_attire(
		"player_attire_chushuijiaolong",
		{
			"target_card":"player",
			"name":"出水姣龙",
			"icon":spr_player_attire_chushuijiaolong_icon,
			"spr":spr_player_attire_chushuijiaolong,
		}
	)
	register_attire(
		"player_attire_baotaotao",
		{
			"target_card":"player",
			"name":"包淘淘",
			"icon":spr_player_attire_baotaotao_icon,
			"spr":spr_player_attire_baotaotao,
		}
	)
	register_attire(
		"player_attire_nanguaqishi",
		{
			"target_card":"player",
			"name":"南瓜骑士",
			"icon":spr_player_attire_nanguaqishi_icon,
			"spr":spr_player_attire_nanguaqishi,
		}
	)
	register_attire(
		"player_attire_weixiandelianren",
		{
			"target_card":"player",
			"name":"危险の 恋人",
			"icon":spr_player_attire_weixiandelianren_icon,
			"spr":spr_player_attire_weixiandelianren,
		}
	)
	register_attire(
		"player_attire_shuangmianshaonv",
		{
			"target_card":"player",
			"name":"双面少女",
			"icon":spr_player_attire_shuangmianshaonv_icon,
			"spr":spr_player_attire_shuangmianshaonv,
		}
	)
	register_attire(
		"player_attire_keaiwawa",
		{
			"target_card":"player",
			"name":"可爱娃娃",
			"icon":spr_player_attire_keaiwawa_icon,
			"spr":spr_player_attire_keaiwawa,
		}
	)
	register_attire(
		"player_attire_hupenghuanyou",
		{
			"target_card":"player",
			"name":"呼朋唤友",
			"icon":spr_player_attire_hupenghuanyou_icon,
			"spr":spr_player_attire_hupenghuanyou,
		}
	)
	register_attire(
		"player_attire_hefugewei",
		{
			"target_card":"player",
			"name":"和服戈薇",
			"icon":spr_player_attire_hefugewei_icon,
			"spr":spr_player_attire_hefugewei,
		}
	)
	register_attire(
		"player_attire_shengdancoser",
		{
			"target_card":"player",
			"name":"圣诞COSER",
			"icon":spr_player_attire_shengdancoser_icon,
			"spr":spr_player_attire_shengdancoser,
		}
	)
	register_attire(
		"player_attire_shengdanxiaomilu",
		{
			"target_card":"player",
			"name":"圣诞小麋鹿",
			"icon":spr_player_attire_shengdanxiaomilu_icon,
			"spr":spr_player_attire_shengdanxiaomilu,
		}
	)
	register_attire(
		"player_attire_diyushaonv",
		{
			"target_card":"player",
			"name":"地狱少女",
			"icon":spr_player_attire_diyushaonv_icon,
			"spr":spr_player_attire_diyushaonv,
		}
	)
	register_attire(
		"player_attire_zhuiruaihe",
		{
			"target_card":"player",
			"name":"坠入爱河",
			"icon":spr_player_attire_zhuiruaihe_icon,
			"spr":spr_player_attire_zhuiruaihe,
		}
	)
	register_attire(
		"player_attire_aijiyanhou",
		{
			"target_card":"player",
			"name":"埃及艳后",
			"icon":spr_player_attire_aijiyanhou_icon,
			"spr":spr_player_attire_aijiyanhou,
		}
	)
	register_attire(
		"player_attire_fuguluolita",
		{
			"target_card":"player",
			"name":"复古洛丽塔",
			"icon":spr_player_attire_fuguluolita_icon,
			"spr":spr_player_attire_fuguluolita,
		}
	)
	register_attire(
		"player_attire_xiariyinghuo",
		{
			"target_card":"player",
			"name":"夏日萤火",
			"icon":spr_player_attire_xiariyinghuo_icon,
			"spr":spr_player_attire_xiariyinghuo,
		}
	)
	register_attire(
		"player_attire_duowanxiaoniu",
		{
			"target_card":"player",
			"name":"多玩小妞",
			"icon":spr_player_attire_duowanxiaoniu_icon,
			"spr":spr_player_attire_duowanxiaoniu,
		}
	)
	register_attire(
		"player_attire_tianshenzhiyingbanbenyi",
		{
			"target_card":"player",
			"name":"天神之影（版本一）",
			"icon":spr_player_attire_tianshenzhiyingbanbenyi_icon,
			"spr":spr_player_attire_tianshenzhiyingbanbenyi,
		}
	)
	register_attire(
		"player_attire_tianshenzhiyingbanbensan",
		{
			"target_card":"player",
			"name":"天神之影（版本三）",
			"icon":spr_player_attire_tianshenzhiyingbanbensan_icon,
			"spr":spr_player_attire_tianshenzhiyingbanbensan,
		}
	)
	register_attire(
		"player_attire_tianshenzhiyingbanbener",
		{
			"target_card":"player",
			"name":"天神之影（版本二）",
			"icon":spr_player_attire_tianshenzhiyingbanbener_icon,
			"spr":spr_player_attire_tianshenzhiyingbanbener,
		}
	)
	register_attire(
		"player_attire_nvpuwawa",
		{
			"target_card":"player",
			"name":"女仆娃娃",
			"icon":spr_player_attire_nvpuwawa_icon,
			"spr":spr_player_attire_nvpuwawa,
		}
	)
	register_attire(
		"player_attire_nvwangmiao",
		{
			"target_card":"player",
			"name":"女王喵",
			"icon":spr_player_attire_nvwangmiao_icon,
			"spr":spr_player_attire_nvwangmiao,
		}
	)
	register_attire(
		"player_attire_shouhuzhishen",
		{
			"target_card":"player",
			"name":"守护之神",
			"icon":spr_player_attire_shouhuzhishen_icon,
			"spr":spr_player_attire_shouhuzhishen,
		}
	)
	register_attire(
		"player_attire_shouhuzhe",
		{
			"target_card":"player",
			"name":"守护者",
			"icon":spr_player_attire_shouhuzhe_icon,
			"spr":spr_player_attire_shouhuzhe,
		}
	)
	register_attire(
		"player_attire_dingzhilifu",
		{
			"target_card":"player",
			"name":"定制礼服",
			"icon":spr_player_attire_dingzhilifu_icon,
			"spr":spr_player_attire_dingzhilifu,
		}
	)
	register_attire(
		"player_attire_gongtingfugu",
		{
			"target_card":"player",
			"name":"宫廷复古",
			"icon":spr_player_attire_gongtingfugu_icon,
			"spr":spr_player_attire_gongtingfugu,
		}
	)
	register_attire(
		"player_attire_xiaochounv",
		{
			"target_card":"player",
			"name":"小丑女",
			"icon":spr_player_attire_xiaochounv_icon,
			"spr":spr_player_attire_xiaochounv,
		}
	)
	register_attire(
		"player_attire_xiaoyi",
		{
			"target_card":"player",
			"name":"小伊",
			"icon":spr_player_attire_xiaoyi_icon,
			"spr":spr_player_attire_xiaoyi,
		}
	)
	register_attire(
		"player_attire_xiaonilu",
		{
			"target_card":"player",
			"name":"小妮露",
			"icon":spr_player_attire_xiaonilu_icon,
			"spr":spr_player_attire_xiaonilu,
		}
	)
	register_attire(
		"player_attire_xiaoxiongmei",
		{
			"target_card":"player",
			"name":"小熊妹~",
			"icon":spr_player_attire_xiaoxiongmei_icon,
			"spr":spr_player_attire_xiaoxiongmei,
		}
	)
	register_attire(
		"player_attire_xiaohongmao",
		{
			"target_card":"player",
			"name":"小红帽",
			"icon":spr_player_attire_xiaohongmao_icon,
			"spr":spr_player_attire_xiaohongmao,
		}
	)
	register_attire(
		"player_attire_xiaohudie",
		{
			"target_card":"player",
			"name":"小蝴蝶",
			"icon":spr_player_attire_xiaohudie_icon,
			"spr":spr_player_attire_xiaohudie,
		}
	)
	register_attire(
		"player_attire_xiaoyenv",
		{
			"target_card":"player",
			"name":"小野女",
			"icon":spr_player_attire_xiaoyenv_icon,
			"spr":spr_player_attire_xiaoyenv,
		}
	)
	register_attire(
		"player_attire_xiaomawei",
		{
			"target_card":"player",
			"name":"小马尾",
			"icon":spr_player_attire_xiaomawei_icon,
			"spr":spr_player_attire_xiaomawei,
		}
	)
	register_attire(
		"player_attire_xiaolongnv",
		{
			"target_card":"player",
			"name":"小龙女",
			"icon":spr_player_attire_xiaolongnv_icon,
			"spr":spr_player_attire_xiaolongnv,
		}
	)
	register_attire(
		"player_attire_midoudou",
		{
			"target_card":"player",
			"name":"弥豆豆",
			"icon":spr_player_attire_midoudou_icon,
			"spr":spr_player_attire_midoudou,
		}
	)
	register_attire(
		"player_attire_caihongshaonv",
		{
			"target_card":"player",
			"name":"彩虹少女",
			"icon":spr_player_attire_caihongshaonv_icon,
			"spr":spr_player_attire_caihongshaonv,
		}
	)
	register_attire(
		"player_attire_caidiejunzhu",
		{
			"target_card":"player",
			"name":"彩蝶郡主",
			"icon":spr_player_attire_caidiejunzhu_icon,
			"spr":spr_player_attire_caidiejunzhu,
		}
	)
	register_attire(
		"player_attire_renzhemiaobanbenyi",
		{
			"target_card":"player",
			"name":"忍者喵（版本一）",
			"icon":spr_player_attire_renzhemiaobanbenyi_icon,
			"spr":spr_player_attire_renzhemiaobanbenyi,
		}
	)
	register_attire(
		"player_attire_kuailemini",
		{
			"target_card":"player",
			"name":"快乐米妮",
			"icon":spr_player_attire_kuailemini_icon,
			"spr":spr_player_attire_kuailemini,
		}
	)
	register_attire(
		"player_attire_dagongtumei",
		{
			"target_card":"player",
			"name":"打工兔妹",
			"icon":spr_player_attire_dagongtumei_icon,
			"spr":spr_player_attire_dagongtumei,
		}
	)
	register_attire(
		"player_attire_zhiaiyongheng",
		{
			"target_card":"player",
			"name":"挚爱永恒",
			"icon":spr_player_attire_zhiaiyongheng_icon,
			"spr":spr_player_attire_zhiaiyongheng,
		}
	)
	register_attire(
		"player_attire_xinnianghunsha",
		{
			"target_card":"player",
			"name":"新娘婚纱",
			"icon":spr_player_attire_xinnianghunsha_icon,
			"spr":spr_player_attire_xinnianghunsha,
		}
	)
	register_attire(
		"player_attire_xinnianleletu",
		{
			"target_card":"player",
			"name":"新年乐乐兔",
			"icon":spr_player_attire_xinnianleletu_icon,
			"spr":spr_player_attire_xinnianleletu,
		}
	)
	register_attire(
		"player_attire_fangkuaigongzhu",
		{
			"target_card":"player",
			"name":"方块公主",
			"icon":spr_player_attire_fangkuaigongzhu_icon,
			"spr":spr_player_attire_fangkuaigongzhu,
		}
	)
	register_attire(
		"player_attire_shijianshen",
		{
			"target_card":"player",
			"name":"时间神",
			"icon":spr_player_attire_shijianshen_icon,
			"spr":spr_player_attire_shijianshen,
		}
	)
	register_attire(
		"player_attire_xingzhihuanbianshen1",
		{
			"target_card":"player",
			"name":"星之焕变身1",
			"icon":spr_player_attire_xingzhihuanbianshen1_icon,
			"spr":spr_player_attire_xingzhihuanbianshen1,
		}
	)
	register_attire(
		"player_attire_xingzhihuanbianshen2",
		{
			"target_card":"player",
			"name":"星之焕变身2",
			"icon":spr_player_attire_xingzhihuanbianshen2_icon,
			"spr":spr_player_attire_xingzhihuanbianshen2,
		}
	)
	register_attire(
		"player_attire_xingzhihuanbianshen3",
		{
			"target_card":"player",
			"name":"星之焕变身3",
			"icon":spr_player_attire_xingzhihuanbianshen3_icon,
			"spr":spr_player_attire_xingzhihuanbianshen3,
		}
	)
	register_attire(
		"player_attire_xingguizhimeng",
		{
			"target_card":"player",
			"name":"星轨织梦",
			"icon":spr_player_attire_xingguizhimeng_icon,
			"spr":spr_player_attire_xingguizhimeng,
		}
	)
	register_attire(
		"player_attire_xingjichuanyue",
		{
			"target_card":"player",
			"name":"星际穿越",
			"icon":spr_player_attire_xingjichuanyue_icon,
			"spr":spr_player_attire_xingjichuanyue,
		}
	)
	register_attire(
		"player_attire_chunrixinyu",
		{
			"target_card":"player",
			"name":"春日心语",
			"icon":spr_player_attire_chunrixinyu_icon,
			"spr":spr_player_attire_chunrixinyu,
		}
	)
	register_attire(
		"player_attire_qingtianmeimei",
		{
			"target_card":"player",
			"name":"晴天美眉",
			"icon":spr_player_attire_qingtianmeimei_icon,
			"spr":spr_player_attire_qingtianmeimei,
		}
	)
	register_attire(
		"player_attire_pengkehushi",
		{
			"target_card":"player",
			"name":"朋克护士",
			"icon":spr_player_attire_pengkehushi_icon,
			"spr":spr_player_attire_pengkehushi,
		}
	)
	register_attire(
		"player_attire_zhuliye",
		{
			"target_card":"player",
			"name":"朱丽叶",
			"icon":spr_player_attire_zhuliye_icon,
			"spr":spr_player_attire_zhuliye,
		}
	)
	register_attire(
		"player_attire_gesanghua",
		{
			"target_card":"player",
			"name":"格桑花",
			"icon":spr_player_attire_gesanghua_icon,
			"spr":spr_player_attire_gesanghua,
		}
	)
	register_attire(
		"player_attire_liangshanpo",
		{
			"target_card":"player",
			"name":"梁珊泊",
			"icon":spr_player_attire_liangshanpo_icon,
			"spr":spr_player_attire_liangshanpo,
		}
	)
	register_attire(
		"player_attire_mengzhihuajia",
		{
			"target_card":"player",
			"name":"梦之花嫁",
			"icon":spr_player_attire_mengzhihuajia_icon,
			"spr":spr_player_attire_mengzhihuajia,
		}
	)
	register_attire(
		"player_attire_menghuanluna",
		{
			"target_card":"player",
			"name":"梦幻露娜",
			"icon":spr_player_attire_menghuanluna_icon,
			"spr":spr_player_attire_menghuanluna,
		}
	)
	register_attire(
		"player_attire_senzhijingling",
		{
			"target_card":"player",
			"name":"森之精灵",
			"icon":spr_player_attire_senzhijingling_icon,
			"spr":spr_player_attire_senzhijingling,
		}
	)
	register_attire(
		"player_attire_yingzhilianqu",
		{
			"target_card":"player",
			"name":"樱之恋曲",
			"icon":spr_player_attire_yingzhilianqu_icon,
			"spr":spr_player_attire_yingzhilianqu,
		}
	)
	register_attire(
		"player_attire_yingtaoxiaobuding",
		{
			"target_card":"player",
			"name":"樱桃小布丁",
			"icon":spr_player_attire_yingtaoxiaobuding_icon,
			"spr":spr_player_attire_yingtaoxiaobuding,
		}
	)
	register_attire(
		"player_attire_huantianxidi",
		{
			"target_card":"player",
			"name":"欢天喜地",
			"icon":spr_player_attire_huantianxidi_icon,
			"spr":spr_player_attire_huantianxidi,
		}
	)
	register_attire(
		"player_attire_maorongmengtu",
		{
			"target_card":"player",
			"name":"毛绒萌兔",
			"icon":spr_player_attire_maorongmengtu_icon,
			"spr":spr_player_attire_maorongmengtu,
		}
	)
	register_attire(
		"player_attire_qianqian",
		{
			"target_card":"player",
			"name":"浅浅",
			"icon":spr_player_attire_qianqian_icon,
			"spr":spr_player_attire_qianqian,
		}
	)
	register_attire(
		"player_attire_huanxiongxiaoniu",
		{
			"target_card":"player",
			"name":"浣熊小妞",
			"icon":spr_player_attire_huanxiongxiaoniu_icon,
			"spr":spr_player_attire_huanxiongxiaoniu,
		}
	)
	register_attire(
		"player_attire_shunvtianxin",
		{
			"target_card":"player",
			"name":"淑女甜心",
			"icon":spr_player_attire_shunvtianxin_icon,
			"spr":spr_player_attire_shunvtianxin,
		}
	)
	register_attire(
		"player_attire_aideluoli",
		{
			"target_card":"player",
			"name":"爱の萝莉",
			"icon":spr_player_attire_aideluoli_icon,
			"spr":spr_player_attire_aideluoli,
		}
	)
	register_attire(
		"player_attire_aisha",
		{
			"target_card":"player",
			"name":"爱莎",
			"icon":spr_player_attire_aisha_icon,
			"spr":spr_player_attire_aisha,
		}
	)
	register_attire(
		"player_attire_maoniang",
		{
			"target_card":"player",
			"name":"猫娘",
			"icon":spr_player_attire_maoniang_icon,
			"spr":spr_player_attire_maoniang,
		}
	)
	register_attire(
		"player_attire_maoyangongzhu",
		{
			"target_card":"player",
			"name":"猫眼公主",
			"icon":spr_player_attire_maoyangongzhu_icon,
			"spr":spr_player_attire_maoyangongzhu,
		}
	)
	register_attire(
		"player_attire_tianxingongzhu",
		{
			"target_card":"player",
			"name":"甜心公主",
			"icon":spr_player_attire_tianxingongzhu_icon,
			"spr":spr_player_attire_tianxingongzhu,
		}
	)
	register_attire(
		"player_attire_shenmimaonv",
		{
			"target_card":"player",
			"name":"神秘猫女",
			"icon":spr_player_attire_shenmimaonv_icon,
			"spr":spr_player_attire_shenmimaonv,
		}
	)
	register_attire(
		"player_attire_zhangyuxiaowanzi",
		{
			"target_card":"player",
			"name":"章鱼小丸子",
			"icon":spr_player_attire_zhangyuxiaowanzi_icon,
			"spr":spr_player_attire_zhangyuxiaowanzi,
		}
	)
	register_attire(
		"player_attire_tongnianlingzi",
		{
			"target_card":"player",
			"name":"童年玲子",
			"icon":spr_player_attire_tongnianlingzi_icon,
			"spr":spr_player_attire_tongnianlingzi,
		}
	)
	register_attire(
		"player_attire_jianyushuangling",
		{
			"target_card":"player",
			"name":"箭羽霜翎",
			"icon":spr_player_attire_jianyushuangling_icon,
			"spr":spr_player_attire_jianyushuangling,
		}
	)
	register_attire(
		"player_attire_miyagongzhu",
		{
			"target_card":"player",
			"name":"米亚公主",
			"icon":spr_player_attire_miyagongzhu_icon,
			"spr":spr_player_attire_miyagongzhu,
		}
	)
	register_attire(
		"player_attire_zongzixiaoni",
		{
			"target_card":"player",
			"name":"粽子小妮",
			"icon":spr_player_attire_zongzixiaoni_icon,
			"spr":spr_player_attire_zongzixiaoni,
		}
	)
	register_attire(
		"player_attire_jinglinggongzhu",
		{
			"target_card":"player",
			"name":"精灵公主",
			"icon":spr_player_attire_jinglinggongzhu_icon,
			"spr":spr_player_attire_jinglinggongzhu,
		}
	)
	register_attire(
		"player_attire_zixia",
		{
			"target_card":"player",
			"name":"紫霞",
			"icon":spr_player_attire_zixia_icon,
			"spr":spr_player_attire_zixia,
		}
	)
	register_attire(
		"player_attire_hongtaoailisi",
		{
			"target_card":"player",
			"name":"红桃爱丽丝",
			"icon":spr_player_attire_hongtaoailisi_icon,
			"spr":spr_player_attire_hongtaoailisi,
		}
	)
	register_attire(
		"player_attire_hongmeigongzhu",
		{
			"target_card":"player",
			"name":"红莓公主",
			"icon":spr_player_attire_hongmeigongzhu_icon,
			"spr":spr_player_attire_hongmeigongzhu,
		}
	)
	register_attire(
		"player_attire_hongmoguannvpu",
		{
			"target_card":"player",
			"name":"红魔馆女仆",
			"icon":spr_player_attire_hongmoguannvpu_icon,
			"spr":spr_player_attire_hongmoguannvpu,
		}
	)
	register_attire(
		"player_attire_hongshutaozhuang",
		{
			"target_card":"player",
			"name":"红鼠套装",
			"icon":spr_player_attire_hongshutaozhuang_icon,
			"spr":spr_player_attire_hongshutaozhuang,
		}
	)
	register_attire(
		"player_attire_zhinv",
		{
			"target_card":"player",
			"name":"织女",
			"icon":spr_player_attire_zhinv_icon,
			"spr":spr_player_attire_zhinv,
		}
	)
	register_attire(
		"player_attire_aimilili",
		{
			"target_card":"player",
			"name":"艾米莉莉",
			"icon":spr_player_attire_aimilili_icon,
			"spr":spr_player_attire_aimilili,
		}
	)
	register_attire(
		"player_attire_babala",
		{
			"target_card":"player",
			"name":"芭芭拉",
			"icon":spr_player_attire_babala_icon,
			"spr":spr_player_attire_babala,
		}
	)
	register_attire(
		"player_attire_yayi",
		{
			"target_card":"player",
			"name":"芽衣",
			"icon":spr_player_attire_yayi_icon,
			"spr":spr_player_attire_yayi,
		}
	)
	register_attire(
		"player_attire_mengtugongzhu",
		{
			"target_card":"player",
			"name":"萌兔公主",
			"icon":spr_player_attire_mengtugongzhu_icon,
			"spr":spr_player_attire_mengtugongzhu,
		}
	)
	register_attire(
		"player_attire_mengniangtaozhuang",
		{
			"target_card":"player",
			"name":"萌娘套装",
			"icon":spr_player_attire_mengniangtaozhuang_icon,
			"spr":spr_player_attire_mengniangtaozhuang,
		}
	)
	register_attire(
		"player_attire_luolimiao",
		{
			"target_card":"player",
			"name":"萝莉喵",
			"icon":spr_player_attire_luolimiao_icon,
			"spr":spr_player_attire_luolimiao,
		}
	)
	register_attire(
		"player_attire_lanseyaoji",
		{
			"target_card":"player",
			"name":"蓝色妖姬",
			"icon":spr_player_attire_lanseyaoji_icon,
			"spr":spr_player_attire_lanseyaoji,
		}
	)
	register_attire(
		"player_attire_qiangweizhilian",
		{
			"target_card":"player",
			"name":"蔷薇之恋",
			"icon":spr_player_attire_qiangweizhilian_icon,
			"spr":spr_player_attire_qiangweizhilian,
		}
	)
	register_attire(
		"player_attire_leileimu",
		{
			"target_card":"player",
			"name":"蕾蕾姆",
			"icon":spr_player_attire_leileimu_icon,
			"spr":spr_player_attire_leileimu,
		}
	)
	register_attire(
		"player_attire_mili",
		{
			"target_card":"player",
			"name":"蜜梨",
			"icon":spr_player_attire_mili_icon,
			"spr":spr_player_attire_mili,
		}
	)
	register_attire(
		"player_attire_mifengxiaojiejie",
		{
			"target_card":"player",
			"name":"蜜蜂小姐姐",
			"icon":spr_player_attire_mifengxiaojiejie_icon,
			"spr":spr_player_attire_mifengxiaojiejie,
		}
	)
	register_attire(
		"player_attire_hudiejiejie",
		{
			"target_card":"player",
			"name":"蝴蝶姐姐",
			"icon":spr_player_attire_hudiejiejie_icon,
			"spr":spr_player_attire_hudiejiejie,
		}
	)
	register_attire(
		"player_attire_dielianhua",
		{
			"target_card":"player",
			"name":"蝶恋花",
			"icon":spr_player_attire_dielianhua_icon,
			"spr":spr_player_attire_dielianhua,
		}
	)
	register_attire(
		"player_attire_changongxianzi",
		{
			"target_card":"player",
			"name":"蟾宫仙子",
			"icon":spr_player_attire_changongxianzi_icon,
			"spr":spr_player_attire_changongxianzi,
		}
	)
	register_attire(
		"player_attire_changongzhegui",
		{
			"target_card":"player",
			"name":"蟾宫折桂",
			"icon":spr_player_attire_changongzhegui_icon,
			"spr":spr_player_attire_changongzhegui,
		}
	)
	register_attire(
		"player_attire_xuesezange",
		{
			"target_card":"player",
			"name":"血色赞歌",
			"icon":spr_player_attire_xuesezange_icon,
			"spr":spr_player_attire_xuesezange,
		}
	)
	register_attire(
		"player_attire_diaochan",
		{
			"target_card":"player",
			"name":"貂婵",
			"icon":spr_player_attire_diaochan_icon,
			"spr":spr_player_attire_diaochan,
		}
	)
	register_attire(
		"player_attire_hesuitongnv",
		{
			"target_card":"player",
			"name":"贺岁童女",
			"icon":spr_player_attire_hesuitongnv_icon,
			"spr":spr_player_attire_hesuitongnv,
		}
	)
	register_attire(
		"player_attire_hemaoshaluo",
		{
			"target_card":"player",
			"name":"贺茂沙罗",
			"icon":spr_player_attire_hemaoshaluo_icon,
			"spr":spr_player_attire_hemaoshaluo,
		}
	)
	register_attire(
		"player_attire_hesitiya",
		{
			"target_card":"player",
			"name":"赫斯提亚",
			"icon":spr_player_attire_hesitiya_icon,
			"spr":spr_player_attire_hesitiya,
		}
	)
	register_attire(
		"player_attire_chaonengshaonv",
		{
			"target_card":"player",
			"name":"超能少女",
			"icon":spr_player_attire_chaonengshaonv_icon,
			"spr":spr_player_attire_chaonengshaonv,
		}
	)
	register_attire(
		"player_attire_chaomengluoli",
		{
			"target_card":"player",
			"name":"超萌萝莉",
			"icon":spr_player_attire_chaomengluoli_icon,
			"spr":spr_player_attire_chaomengluoli,
		}
	)
	register_attire(
		"player_attire_miwushutongren",
		{
			"target_card":"player",
			"name":"迷雾鼠同人",
			"icon":spr_player_attire_miwushutongren_icon,
			"spr":spr_player_attire_miwushutongren,
		}
	)
	register_attire(
		"player_attire_jinfenjiaren",
		{
			"target_card":"player",
			"name":"金粉佳人",
			"icon":spr_player_attire_jinfenjiaren_icon,
			"spr":spr_player_attire_jinfenjiaren,
		}
	)
	register_attire(
		"player_attire_jinseshiyan",
		{
			"target_card":"player",
			"name":"金色誓言",
			"icon":spr_player_attire_jinseshiyan_icon,
			"spr":spr_player_attire_jinseshiyan,
		}
	)
	register_attire(
		"player_attire_lingyinnuanxinnian",
		{
			"target_card":"player",
			"name":"铃音暖新年",
			"icon":spr_player_attire_lingyinnuanxinnian_icon,
			"spr":spr_player_attire_lingyinnuanxinnian,
		}
	)
	register_attire(
		"player_attire_jinxiufuxing",
		{
			"target_card":"player",
			"name":"锦绣福星",
			"icon":spr_player_attire_jinxiufuxing_icon,
			"spr":spr_player_attire_jinxiufuxing,
		}
	)
	register_attire(
		"player_attire_jinlixiaojiejie",
		{
			"target_card":"player",
			"name":"锦鲤小姐姐",
			"icon":spr_player_attire_jinlixiaojiejie_icon,
			"spr":spr_player_attire_jinlixiaojiejie,
		}
	)
	register_attire(
		"player_attire_shanliangnvzhubo",
		{
			"target_card":"player",
			"name":"闪亮女主播",
			"icon":spr_player_attire_shanliangnvzhubo_icon,
			"spr":spr_player_attire_shanliangnvzhubo,
		}
	)
	register_attire(
		"player_attire_shanliangnvmingxing",
		{
			"target_card":"player",
			"name":"闪亮女明星",
			"icon":spr_player_attire_shanliangnvmingxing_icon,
			"spr":spr_player_attire_shanliangnvmingxing,
		}
	)
	register_attire(
		"player_attire_ali",
		{
			"target_card":"player",
			"name":"阿狸",
			"icon":spr_player_attire_ali_icon,
			"spr":spr_player_attire_ali,
		}
	)
	register_attire(
		"player_attire_aligaduo",
		{
			"target_card":"player",
			"name":"阿里嘎多",
			"icon":spr_player_attire_aligaduo_icon,
			"spr":spr_player_attire_aligaduo,
		}
	)
	register_attire(
		"player_attire_xueyushuanghua",
		{
			"target_card":"player",
			"name":"雪域霜花",
			"icon":spr_player_attire_xueyushuanghua_icon,
			"spr":spr_player_attire_xueyushuanghua,
		}
	)
	register_attire(
		"player_attire_qingqingzijin",
		{
			"target_card":"player",
			"name":"青青子衿",
			"icon":spr_player_attire_qingqingzijin_icon,
			"spr":spr_player_attire_qingqingzijin,
		}
	)
	register_attire(
		"player_attire_qingluanzhiling",
		{
			"target_card":"player",
			"name":"青鸾之灵",
			"icon":spr_player_attire_qingluanzhiling_icon,
			"spr":spr_player_attire_qingluanzhiling,
		}
	)
	register_attire(
		"player_attire_mianjushaonv",
		{
			"target_card":"player",
			"name":"面具少女",
			"icon":spr_player_attire_mianjushaonv_icon,
			"spr":spr_player_attire_mianjushaonv,
		}
	)
	register_attire(
		"player_attire_mianfendaidaizi",
		{
			"target_card":"player",
			"name":"面粉袋袋子",
			"icon":spr_player_attire_mianfendaidaizi_icon,
			"spr":spr_player_attire_mianfendaidaizi,
		}
	)
	register_attire(
		"player_attire_feiniaoyuyu",
		{
			"target_card":"player",
			"name":"飞鸟与鱼",
			"icon":spr_player_attire_feiniaoyuyu_icon,
			"spr":spr_player_attire_feiniaoyuyu,
		}
	)
	register_attire(
		"player_attire_xiangshuibaihe",
		{
			"target_card":"player",
			"name":"香水百合",
			"icon":spr_player_attire_xiangshuibaihe_icon,
			"spr":spr_player_attire_xiangshuibaihe,
		}
	)
	register_attire(
		"player_attire_guijishishen",
		{
			"target_card":"player",
			"name":"鬼姬式神",
			"icon":spr_player_attire_guijishishen_icon,
			"spr":spr_player_attire_guijishishen,
		}
	)
	register_attire(
		"player_attire_molishaonv",
		{
			"target_card":"player",
			"name":"魔力少女",
			"icon":spr_player_attire_molishaonv_icon,
			"spr":spr_player_attire_molishaonv,
		}
	)
	register_attire(
		"player_attire_monvling",
		{
			"target_card":"player",
			"name":"魔女「零」",
			"icon":spr_player_attire_monvling_icon,
			"spr":spr_player_attire_monvling,
		}
	)
	register_attire(
		"player_attire_moyingshengyiyiji",
		{
			"target_card":"player",
			"name":"魔影圣衣一级",
			"icon":spr_player_attire_moyingshengyiyiji_icon,
			"spr":spr_player_attire_moyingshengyiyiji,
		}
	)
	register_attire(
		"player_attire_moyingshengyierji",
		{
			"target_card":"player",
			"name":"魔影圣衣二级",
			"icon":spr_player_attire_moyingshengyierji_icon,
			"spr":spr_player_attire_moyingshengyierji,
		}
	)
	register_attire(
		"player_attire_mofaxueyuan",
		{
			"target_card":"player",
			"name":"魔法学院",
			"icon":spr_player_attire_mofaxueyuan_icon,
			"spr":spr_player_attire_mofaxueyuan,
		}
	)
	register_attire(
		"player_attire_mofashaonv",
		{
			"target_card":"player",
			"name":"魔法少女",
			"icon":spr_player_attire_mofashaonv_icon,
			"spr":spr_player_attire_mofashaonv,
		}
	)
	register_attire(
		"player_attire_queqiaomiaomiao",
		{
			"target_card":"player",
			"name":"鹊桥喵喵",
			"icon":spr_player_attire_queqiaomiaomiao_icon,
			"spr":spr_player_attire_queqiaomiaomiao,
		}
	)
	register_attire(
		"player_attire_longnv",
		{
			"target_card":"player",
			"name":"龙女",
			"icon":spr_player_attire_longnv_icon,
			"spr":spr_player_attire_longnv,
		}
	)
	register_attire(
		"player_attire_longzhouamei",
		{
			"target_card":"player",
			"name":"龙舟阿妹",
			"icon":spr_player_attire_longzhouamei_icon,
			"spr":spr_player_attire_longzhouamei,
		}
	)
}