image_xscale = 1.8;
image_yscale = 1.8;
image_speed = 0;
on_click = false;
gem_id = "zeus_ren_gem";
gem_info = get_gem_info(gem_id);
gem_level = clamp(get_gem_level(gem_id), 0, gem_info.max_level);
cooldown = 0;
cooldown_timer = 0;
