function obj_pool_build_deck_map() {
    var _m = {};
    _m[$ "obj_12yinliao"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_aladdin_lamp"] = [obj_aladdin_lamp_bullet];
    _m[$ "obj_aquarius_elve"] = [obj_mouse_ash_death, obj_wine_bottle_bomb_explode];
    _m[$ "obj_arno"] = [obj_arno_bullet];
    _m[$ "obj_arno_bullet"] = [obj_arno_bullet_effect];
    _m[$ "obj_arson_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_arson_mouse"] = [obj_arson_bullet];
    _m[$ "obj_athena"] = [obj_athena_bullet];
    _m[$ "obj_aurora"] = [obj_aurora_dead_explode, obj_mouse_ash_death];
    _m[$ "obj_beef_hotpot"] = [obj_beefhotpot_bullet];
    _m[$ "obj_beefhotpot_bullet"] = [obj_mouse_ash_death];
    _m[$ "obj_blonde_mary"] = [obj_blonde_mary_bullet];
    _m[$ "obj_bomb_gem_effect"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_brahma"] = [obj_mouse_ash_death];
    _m[$ "obj_bubble_gun"] = [obj_coffeepot_bullet];
    _m[$ "obj_bull_firework"] = [obj_coke_bomb_explode];
    _m[$ "obj_burn_effect"] = [obj_mouse_ash_death];
    _m[$ "obj_captain_america_mouse"] = [obj_coke_bomb_explode];
    _m[$ "obj_cat_gun"] = [obj_catgun_bullet];
    _m[$ "obj_chili_powder"] = [obj_coke_bomb_explode, obj_mouse_ash_death, obj_wine_bottle_bomb_explode];
    _m[$ "obj_chocolate_cannon"] = [obj_chocolatecannon_bullet];
    _m[$ "obj_chocolate_pult"] = [obj_chocolatepult_bullet];
    _m[$ "obj_chocolatecannon_bullet"] = [obj_chocolatecannon_bullet_effect, obj_mouse_ash_death];
    _m[$ "obj_chocolatepult_bullet"] = [obj_coffeecup_bullet_effect];
    _m[$ "obj_cloud"] = [obj_drop_death_effect];
    _m[$ "obj_coal_starfish"] = [obj_coalstarfish_bullet];
    _m[$ "obj_coalstarfish_bullet"] = [obj_coke_bomb_explode, obj_fire_bullet_effect];
    _m[$ "obj_coffee_cup"] = [obj_coffeecup_bullet];
    _m[$ "obj_coffee_pot"] = [obj_coffeepot_bullet];
    _m[$ "obj_coffeecup_bullet"] = [obj_coffeecup_bullet_effect];
    _m[$ "obj_coke_bomb"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_cold_drew"] = [obj_cold_drew_bullet];
    _m[$ "obj_conch_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_conch_mouse"] = [obj_conch_bullet];
    _m[$ "obj_corn_shooter"] = [obj_corn_shooter_bullet];
    _m[$ "obj_corn_shooter_bullet"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_corn_shooter_bullet_1"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_corn_shooter_bullet_2"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_curry_lobster_cannon"] = [obj_currylobstercannon_bullet];
    _m[$ "obj_currylobstercannon_bullet"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_dandantu"] = [obj_bullet_parent, obj_dandantu_bullet];
    _m[$ "obj_delicacy_firework"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_donut"] = [obj_donut_bullet];
    _m[$ "obj_donut_bullet"] = [obj_xiaolongbao_bullet_effect];
    _m[$ "obj_double_blade_snake"] = [obj_double_blade_snake_bullet];
    _m[$ "obj_double_blade_snake_bullet"] = [obj_mouse_ash_death];
    _m[$ "obj_double_ice_crossbow"] = [obj_iceeggboilerpult_bullet];
    _m[$ "obj_double_ice_long_bao"] = [obj_icelongbao_bullet];
    _m[$ "obj_double_long_bao"] = [obj_xiaolongbao_bullet];
    _m[$ "obj_double_water_gun"] = [obj_waterpipe_bullet];
    _m[$ "obj_double_water_pipe"] = [obj_waterpipe_bullet];
    _m[$ "obj_eel_mouse"] = [obj_eel_bullet];
    _m[$ "obj_egg_boiler_pult"] = [obj_eggboilerpult_bullet];
    _m[$ "obj_eggboilerpult_bullet"] = [obj_eggboilerpult_bullet_effect];
    _m[$ "obj_electric_jellyfish"] = [obj_electric_jellyfish_bullet];
    _m[$ "obj_engineer_bullet"] = [obj_engineer_bullet_effect];
    _m[$ "obj_engineering_vehicle_mouse"] = [obj_engineer_bullet];
    _m[$ "obj_enhanced_howitzer"] = [obj_howitzer_bullet];
    _m[$ "obj_gaia"] = [obj_gaia_bullet];
    _m[$ "obj_gaia_bullet"] = [obj_gaia_bullet_effect, obj_mouse_ash_death];
    _m[$ "obj_gatlin_ice_long_bao"] = [obj_icelongbao_bullet];
    _m[$ "obj_gatlin_long_bao"] = [obj_xiaolongbao_bullet];
    _m[$ "obj_ghost_god"] = [obj_ghost_god_bullet_ping, obj_ghost_god_bullet_ping_m, obj_ghost_god_bullet_xie, obj_ghost_god_bullet_xie_m, obj_ghost_god_bullet_zhi, obj_ghost_god_bullet_zhi_m];
    _m[$ "obj_ghost_god_bullet_ping"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_ghost_god_bullet_ping_m"] = [obj_fire_bullet_effect];
    _m[$ "obj_ghost_god_bullet_xie"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_ghost_god_bullet_xie_m"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_ghost_god_bullet_zhi"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_ghost_god_bullet_zhi_m"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_gongjiang_god"] = [obj_gongjiang_god_bullet_horizontal, obj_gongjiang_god_bullet_vertical];
    _m[$ "obj_grilled_lizard_pult"] = [obj_grilledlizardpult_bullet];
    _m[$ "obj_grilledlizardpult_bullet"] = [obj_grilledlizardpult_bullet_effect];
    _m[$ "obj_guangming_god"] = [obj_guangming_god_bullet, obj_mouse_ash_death];
    _m[$ "obj_hades_scythe"] = [obj_hades_scythe_bullet];
    _m[$ "obj_hamburger"] = [obj_stinkytofupult_bullet_effect];
    _m[$ "obj_hazelnut_cannon_mouse"] = [obj_engineer_bullet];
    _m[$ "obj_heian_god"] = [obj_heian_god_bullet];
    _m[$ "obj_heian_god_bullet"] = [obj_mouse_ash_death];
    _m[$ "obj_hera"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_honglonglong_missile"] = [obj_arno_bullet_effect];
    _m[$ "obj_hotdog_cannon"] = [obj_hotdogcannon_bullet];
    _m[$ "obj_hotdogcannon_bullet"] = [obj_xiaolongbao_bullet_effect];
    _m[$ "obj_houyi_god"] = [obj_houyi_god_bullet];
    _m[$ "obj_houyi_god_bullet"] = [obj_mouse_ash_death];
    _m[$ "obj_houyi_god_fire"] = [obj_mouse_ash_death];
    _m[$ "obj_howitzer"] = [obj_howitzer_bullet];
    _m[$ "obj_howitzer_bullet"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_huang_xiaoming"] = [obj_coke_bomb_explode];
    _m[$ "obj_hufa_god"] = [obj_hufa_god_bullet];
    _m[$ "obj_hulk_mouse"] = [obj_coke_bomb_explode];
    _m[$ "obj_hundun_god"] = [obj_mouse_ash_death];
    _m[$ "obj_ice_bucket_bomb"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_ice_egg_boiler_pult"] = [obj_iceeggboilerpult_bullet];
    _m[$ "obj_ice_god"] = [obj_ice_god_bullet];
    _m[$ "obj_ice_gun"] = [obj_icegun_bullet];
    _m[$ "obj_ice_long_bao"] = [obj_icelongbao_bullet];
    _m[$ "obj_ice_mighty_gun"] = [obj_icegun_bullet];
    _m[$ "obj_ice_residue"] = [obj_ice_residue_bullet];
    _m[$ "obj_ice_residue_bullet"] = [obj_engineer_bullet_effect];
    _m[$ "obj_ice_spoon_crossbow"] = [obj_iceeggboilerpult_bullet];
    _m[$ "obj_iceeggboilerpult_bullet"] = [obj_eggboilerpult_bullet_effect, obj_iceeggboilerpult_bullet_effect];
    _m[$ "obj_icegun_bullet"] = [obj_fire_bullet_effect, obj_icelongbao_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_icelongbao_bullet"] = [obj_fire_bullet_effect, obj_icelongbao_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_icelongbao_bullet_vertical"] = [obj_fire_bullet_effect, obj_icelongbao_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_infected_arno"] = [obj_arno_bullet];
    _m[$ "obj_infected_bingzha"] = [obj_infected_bingzha_bullet];
    _m[$ "obj_infected_bingzha_bullet"] = [obj_engineer_bullet_effect];
    _m[$ "obj_infected_fire_residue"] = [obj_infected_bingzha_bullet];
    _m[$ "obj_infected_zhanshen_bullet"] = [obj_fire_bullet_effect, obj_infected_zhanshen_bullet_effect];
    _m[$ "obj_infected_zhanshen_bullet_super"] = [obj_fire_bullet_effect, obj_infected_zhanshen_bullet_effect];
    _m[$ "obj_iron_man"] = [obj_coke_bomb_explode];
    _m[$ "obj_iron_man_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_iron_man_mouse"] = [obj_coke_bomb_explode, obj_iron_man_bullet];
    _m[$ "obj_irritable_jack_fire_mouse"] = [obj_wine_bottle_bomb_explode];
    _m[$ "obj_joker"] = [obj_joker_bullet, obj_joker_bullet_1, obj_joker_bullet_2, obj_joker_bullet_3];
    _m[$ "obj_joker_bullet"] = [obj_xiaolongbao_bullet_effect];
    _m[$ "obj_joker_bullet_1"] = [obj_joker_bullet_effect_1, obj_mouse_ash_death_1];
    _m[$ "obj_joker_bullet_2"] = [obj_joker_bullet_effect_23, obj_mouse_ash_death_2];
    _m[$ "obj_joker_bullet_3"] = [obj_joker_bullet_effect_23, obj_mouse_ash_death_3];
    _m[$ "obj_julie_missile"] = [obj_wine_bottle_bomb_explode];
    _m[$ "obj_juxie"] = [obj_juxie_bullet_1, obj_juxie_bullet_2];
    _m[$ "obj_juxie_bullet_1"] = [obj_takoyaki_bullet_effect];
    _m[$ "obj_juxie_bullet_2"] = [obj_takoyaki_bullet_effect];
    _m[$ "obj_kamikaze_glider_mouse"] = [obj_coke_bomb_explode];
    _m[$ "obj_kettle_bomb"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_king_long_bao"] = [obj_icelongbao_bullet, obj_xiaolongbao_bullet];
    _m[$ "obj_king_triple_long_bao"] = [obj_icelongbao_bullet, obj_icelongbao_bullet_vertical, obj_xiaolongbao_bullet, obj_xiaolongbao_bullet_vertical];
    _m[$ "obj_laipishe"] = [obj_laipishe_bullet];
    _m[$ "obj_landmine_vehicle_mouse"] = [obj_engineer_bullet];
    _m[$ "obj_lantern_burn_effect"] = [obj_mouse_ash_death];
    _m[$ "obj_laser_gem_effect"] = [obj_mouse_ash_death];
    _m[$ "obj_lieutenant_buzz"] = [obj_arno_bullet_effect];
    _m[$ "obj_lightning_baguette"] = [obj_mouse_ash_death];
    _m[$ "obj_lobster_knight"] = [obj_coke_bomb_explode, obj_lobster_knight_bullet];
    _m[$ "obj_lobster_knight_bullet"] = [obj_coke_bomb_explode, obj_lobster_knight_bullet_extend];
    _m[$ "obj_lobster_knight_bullet_extend"] = [obj_lobster_knight_bullet_extend];
    _m[$ "obj_long_bao_gun"] = [obj_xiaolongbao_bullet];
    _m[$ "obj_love_god"] = [obj_love_god_bullet, obj_love_god_bullet_super];
    _m[$ "obj_love_god_bullet"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_love_god_bullet_1"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_love_god_bullet_2"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_love_god_bullet_3"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_machine_bomb_mouse"] = [obj_machine_bomb_mouse_bullet];
    _m[$ "obj_machine_bomb_mouse_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_machine_mouse"] = [obj_coke_bomb_explode];
    _m[$ "obj_machine_shark_1"] = [obj_shark_1_bullet];
    _m[$ "obj_mermaid_mary"] = [obj_mermaid_mary_bullet];
    _m[$ "obj_mermaid_mary_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_messenger_poop"] = [obj_engineer_bullet_effect];
    _m[$ "obj_mighty_gun"] = [obj_mightygun_bullet];
    _m[$ "obj_mightygun_bullet"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_mojie"] = [obj_mojie_bullet];
    _m[$ "obj_moon_god"] = [obj_moon_god_bullet, obj_moon_god_bullet_super];
    _m[$ "obj_moon_god_bullet"] = [obj_takoyaki_bullet_effect];
    _m[$ "obj_moon_god_bullet_super"] = [obj_takoyaki_bullet_effect];
    _m[$ "obj_mouse_clip"] = [obj_mouse_ash_death, obj_mouse_clip_explode];
    _m[$ "obj_mouse_train_1_bullet"] = [obj_arno_bullet_effect];
    _m[$ "obj_mouse_train_1_head"] = [obj_mouse_train_1_bullet];
    _m[$ "obj_mouse_train_2_body"] = [obj_mouse_train_2_bullet];
    _m[$ "obj_mouse_train_2_bullet"] = [obj_arno_bullet_effect];
    _m[$ "obj_mouse_train_2_head"] = [obj_coke_bomb_explode];
    _m[$ "obj_mouse_train_3_explode"] = [obj_coke_bomb_explode];
    _m[$ "obj_mouse_train_3_head"] = [obj_mouse_train_3_explode];
    _m[$ "obj_obstacle"] = [obj_bullet_parent];
    _m[$ "obj_oden_pot"] = [obj_coffeepot_bullet, obj_odenpot_bullet_vertical];
    _m[$ "obj_odin"] = [obj_odin_bullet];
    _m[$ "obj_odin_bullet"] = [obj_fire_bullet_effect];
    _m[$ "obj_pan_fried_bun"] = [obj_panfriedbun_bullet];
    _m[$ "obj_panduola_god"] = [obj_coke_bomb_explode];
    _m[$ "obj_panfriedbun_bullet"] = [obj_panfriedbun_bullet_effect];
    _m[$ "obj_panfriedbun_bullet_effect"] = [obj_mouse_ash_death];
    _m[$ "obj_paul_bullet"] = [obj_paul_bullet_effect];
    _m[$ "obj_penguin_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_penguin_mouse"] = [obj_penguin_bullet];
    _m[$ "obj_pete_missile"] = [obj_arno_bullet_effect];
    _m[$ "obj_pineapple_explosive_bread_explosion"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_pink_paul"] = [obj_paul_bullet];
    _m[$ "obj_pizza_oven"] = [obj_pizzaoven_bullet];
    _m[$ "obj_player_character"] = [obj_xiaolongbao_bullet];
    _m[$ "obj_player_shield"] = [obj_rose_shield_bullet, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_poseidon"] = [obj_takoyaki_bullet];
    _m[$ "obj_poseidon_dart_gun"] = [obj_takoyaki_bullet];
    _m[$ "obj_power_god"] = [obj_power_god_bullet, obj_power_god_bullet_1];
    _m[$ "obj_power_god_bullet"] = [obj_power_god_bullet_effect];
    _m[$ "obj_power_god_bullet_1"] = [obj_mouse_ash_death, obj_power_god_bullet_effect];
    _m[$ "obj_rabbit_lantern"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_rig"] = [obj_rig_bullet, obj_rig_bullet_oblique];
    _m[$ "obj_rumble_missile"] = [obj_arno_bullet_effect];
    _m[$ "obj_salad_pult"] = [obj_saladpult_bullet];
    _m[$ "obj_saladpult_bullet"] = [obj_saladpult_bullet_effect];
    _m[$ "obj_sausage"] = [obj_sausage_bullet];
    _m[$ "obj_sausage_bullet"] = [obj_xiaolongbao_bullet_effect];
    _m[$ "obj_sh_b_1"] = [obj_mouse_ash_death];
    _m[$ "obj_sh_b_2"] = [obj_mouse_ash_death];
    _m[$ "obj_sh_b_3"] = [obj_mouse_ash_death];
    _m[$ "obj_shark_1_bullet"] = [obj_coke_bomb_explode];
    _m[$ "obj_shennong_god"] = [obj_shennong_god_bullet_h];
    _m[$ "obj_shennong_god_bullet_h"] = [obj_mouse_ash_death];
    _m[$ "obj_shennong_god_bullet_v"] = [obj_mouse_ash_death];
    _m[$ "obj_sheshou"] = [obj_sheshou_bullet];
    _m[$ "obj_sheshou_bullet"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_shuangyu"] = [obj_shuangyu_bullet];
    _m[$ "obj_shuangyu_bullet"] = [obj_iceeggboilerpult_bullet_effect, obj_shuangyu_bullet_effect];
    _m[$ "obj_shuiping"] = [obj_mouse_ash_death, obj_shuiping_explode, obj_wine_bottle_bomb_explode];
    _m[$ "obj_skewer_bomb"] = [obj_coke_bomb_explode, obj_mouse_ash_death];
    _m[$ "obj_spicy_pot"] = [obj_spicypot_bullet];
    _m[$ "obj_spicypot_bullet"] = [obj_mouse_ash_death];
    _m[$ "obj_spider_man_mouse"] = [obj_coke_bomb_explode];
    _m[$ "obj_spider_man_mouse_web"] = [obj_coke_bomb_explode];
    _m[$ "obj_spoon_rabbit"] = [obj_spoon_rabbit_bullet];
    _m[$ "obj_spoon_rabbit_bullet"] = [obj_spoon_rabbit_bullet_effect];
    _m[$ "obj_star_gun"] = [obj_xiaolongbao_bullet];
    _m[$ "obj_star_wand"] = [obj_star_wand_bullet];
    _m[$ "obj_steel_claw_gun"] = [obj_waterpipe_bullet];
    _m[$ "obj_stinky_tofu_pult"] = [obj_stinkytofupult_bullet];
    _m[$ "obj_stinkytofupult_bullet"] = [obj_saladpult_bullet_effect, obj_stinkytofupult_bullet_effect];
    _m[$ "obj_sugar_ball_pult"] = [obj_sugarballpult_bullet];
    _m[$ "obj_sugarballpult_bullet"] = [obj_coke_bomb_explode, obj_eggboilerpult_bullet_effect];
    _m[$ "obj_takoyaki"] = [obj_takoyaki_bullet];
    _m[$ "obj_takoyaki_bullet"] = [obj_takoyaki_bullet_effect];
    _m[$ "obj_tang_hu_lu"] = [obj_tanghulu_bullet];
    _m[$ "obj_tanghulu_bullet"] = [obj_tanghulu_bullet_effect];
    _m[$ "obj_tar_sprayer"] = [obj_tarsprayer_bullet];
    _m[$ "obj_thor"] = [obj_thor_bullet];
    _m[$ "obj_thor_body"] = [obj_coke_bomb_explode];
    _m[$ "obj_thor_bullet"] = [obj_iceeggboilerpult_bullet_effect, obj_thor_bullet_effect_1];
    _m[$ "obj_thor_head"] = [obj_coke_bomb_explode];
    _m[$ "obj_tiancheng"] = [obj_tiancheng_bullet];
    _m[$ "obj_tiancheng_bullet"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_triple_ice_long_bao"] = [obj_icelongbao_bullet, obj_icelongbao_bullet_vertical];
    _m[$ "obj_triple_long_bao"] = [obj_xiaolongbao_bullet, obj_xiaolongbao_bullet_vertical];
    _m[$ "obj_triple_wine_rack"] = [obj_triplewinerack_bullet];
    _m[$ "obj_triplewinerack_bullet"] = [obj_coffeecup_bullet_effect, obj_fire_bullet_effect];
    _m[$ "obj_undersea_penguin_mouse"] = [obj_penguin_bullet];
    _m[$ "obj_war1_god"] = [obj_war_god_bullet, obj_war_god_bullet_super];
    _m[$ "obj_war_god_bullet"] = [obj_fire_bullet_effect, obj_war_god_bullet_effect];
    _m[$ "obj_war_god_bullet_super"] = [obj_fire_bullet_effect, obj_war_god_bullet_effect];
    _m[$ "obj_water_penguin_mouse"] = [obj_penguin_bullet];
    _m[$ "obj_water_tea_cup"] = [obj_coffeecup_bullet];
    _m[$ "obj_waterpipe_bullet"] = [obj_fire_bullet_effect, obj_waterpipe_bullet_effect];
    _m[$ "obj_whisky_bomb"] = [obj_mouse_ash_death, obj_wine_bottle_bomb_explode];
    _m[$ "obj_wine_bottle_bomb"] = [obj_mouse_ash_death, obj_wine_bottle_bomb_explode];
    _m[$ "obj_wine_bottle_bomb_explode"] = [obj_wine_bottle_bomb_explode];
    _m[$ "obj_xiangshui_god"] = [obj_mouse_ash_death];
    _m[$ "obj_xiao_long_bao"] = [obj_xiaolongbao_bullet];
    _m[$ "obj_xiaolongbao_bullet"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_xiaolongbao_bullet_vertical"] = [obj_fire_bullet_effect, obj_xiaolongbao_bullet_effect];
    _m[$ "obj_ymir"] = [obj_ymir_bullet];
    _m[$ "obj_ymir_bullet"] = [obj_iceeggboilerpult_bullet_effect, obj_mouse_ash_death];
    _m[$ "obj_zeus"] = [obj_zeus_bullet];
    _m[$ "obj_zeus_bolt"] = [obj_zeus_bolt_bullet];
    _m[$ "obj_zeus_bolt_bullet"] = [obj_zeus_bolt_bullet_effect];
    _m[$ "obj_zeus_bullet"] = [obj_mouse_ash_death];
    _m[$ "obj_zhurong"] = [obj_zhurong_bullet];
    _m[$ "obj_zhurong_bullet"] = [obj_zhurong_bullet_effect];
    _m[$ "obj_zhurong_bullet_effect"] = [obj_mouse_ash_death];
    return _m;
}

function obj_pool_prewarm_deck() {
    if (!variable_global_exists("_obj_pool_ready") || !global._obj_pool_ready) obj_pool_init();
    if (!variable_global_exists("obj_pool_deck_prewarm")) global.obj_pool_deck_prewarm = 25;
    if (!variable_global_exists("obj_pool_prewarm_per_frame")) global.obj_pool_prewarm_per_frame = 8;

    global._obj_pool_prewarm_queue = [];

    var _count = global.obj_pool_deck_prewarm;
    if (_count <= 0) return;
    if (!variable_global_exists("_obj_pool_deck_map")) global._obj_pool_deck_map = obj_pool_build_deck_map();
    if (!variable_global_exists("selected_deck")) return;

    var _done = ds_map_create();
    for (var i = 0; i < ds_list_size(global.selected_deck); i++) {
        var _e = global.selected_deck[| i];
        if (!ds_exists(_e, ds_type_map)) continue;
        if (!ds_map_exists(_e, "data")) continue;
        var _data = _e[? "data"];
        if (!ds_exists(_data, ds_type_map)) continue;
        if (!ds_map_exists(_data, "obj")) continue;
        var _plant = _data[? "obj"];
        if (!is_real(_plant) || _plant < 0) continue;
        var _name = object_get_name(_plant);
        if (!variable_struct_exists(global._obj_pool_deck_map, _name)) continue;
        var _bullets = global._obj_pool_deck_map[$ _name];
        for (var j = 0; j < array_length(_bullets); j++) {
            var _b = _bullets[j];
            if (!is_real(_b) || _b < 0) continue;
            var _bk = string(_b);
            if (ds_map_exists(_done, _bk)) continue;
            ds_map_add(_done, _bk, true);
            array_push(global._obj_pool_prewarm_queue, [_b, _count]);
        }
    }
    ds_map_destroy(_done);
    obj_pool_prewarm_tick();
}

function obj_pool_prewarm_tick() {
    if (!variable_global_exists("_obj_pool_prewarm_queue") || !is_array(global._obj_pool_prewarm_queue)) return;
    var _q = global._obj_pool_prewarm_queue;
    var _budget = global.obj_pool_prewarm_per_frame;
    for (var i = array_length(_q) - 1; i >= 0 && _budget > 0; i--) {
        var _item = _q[i];
        obj_pool_prealloc(_item[0], 1);
        _item[1] -= 1;
        _budget -= 1;
        if (_item[1] <= 0) array_delete(_q, i, 1);
    }
    if (array_length(_q) == 0) global._obj_pool_prewarm_queue = [];
}
