
draw_set_colour(c_black)
draw_set_alpha(0.5)
draw_rectangle(0,0,room_width,room_height,0)
draw_set_font(font_yuan)
draw_set_colour(c_white)
draw_set_valign(fa_middle)
draw_set_halign(fa_center)
draw_set_alpha(1)
draw_text(room_width/2,room_height/2,"加载中\n预计需要等待15秒\n加载过程中出现的无响应状况为正常现象")
